/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.insoft.archive.db;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Благодатских С.
 */
public class Converter extends javax.swing.JFrame {

	/**
	 * Creates new form Converter
	 */
	public Converter() {
		initComponents();
		chooser = new JFileChooser();
		chooser.setAcceptAllFileFilterUsed(false);
		dbFileEdit.getDocument().addDocumentListener(new DocumentListener() {

			@Override
			public void insertUpdate(DocumentEvent e) {
				setExecEnabled();
			}

			@Override
			public void removeUpdate(DocumentEvent e) {
				setExecEnabled();
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				setExecEnabled();
			}
		});

		dstDirEdit.getDocument().addDocumentListener(new DocumentListener() {

			@Override
			public void insertUpdate(DocumentEvent e) {
				setExecEnabled();
			}

			@Override
			public void removeUpdate(DocumentEvent e) {
				setExecEnabled();
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				setExecEnabled();
			}
		});

	}

	private void setExecEnabled() {

		String srcFileName = dbFileEdit.getText();
		String dstDirName = dstDirEdit.getText();
		if (srcFileName.isEmpty() || dstDirName.isEmpty()) {
			execButton.setEnabled(false);
		} else {
			Path srcFile = Paths.get(srcFileName);
			execButton.setEnabled(Files.isRegularFile(srcFile) && Files.isReadable(srcFile)
					&& Files.isDirectory(Paths.get(dstDirName)));
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbFileEdit = new javax.swing.JTextField();
        dbFileChoose = new javax.swing.JButton();
        dstDirEdit = new javax.swing.JTextField();
        dstDirChoose = new javax.swing.JButton();
        execButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Конвертер данных из MS Access в ВККС");

        dbFileEdit.setToolTipText("Путь к файлу с БД MS Access");

        dbFileChoose.setText("Выбрать файл БД");
        dbFileChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbFileChooseActionPerformed(evt);
            }
        });

        dstDirChoose.setText("Выбрать папку");
        dstDirChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstDirChooseActionPerformed(evt);
            }
        });

        execButton.setText("Преобразовать");
        execButton.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dstDirEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(dbFileEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(execButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dbFileChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dstDirChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbFileEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbFileChoose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dstDirEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dstDirChoose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(execButton)
                .addContainerGap())
        );

        dbFileEdit.getAccessibleContext().setAccessibleName("dbFileEdit");
        dbFileChoose.getAccessibleContext().setAccessibleDescription("Выбор файла с исходными данными");
        dstDirEdit.getAccessibleContext().setAccessibleName("dstDirEdit");
        dstDirEdit.getAccessibleContext().setAccessibleDescription("Путь к преобразованным данным");
        dstDirChoose.getAccessibleContext().setAccessibleDescription("Выбор папки назначения");
        execButton.getAccessibleContext().setAccessibleName("execButton");
        execButton.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbFileChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbFileChooseActionPerformed
		chooser.setDialogTitle("Выбор файла с БД MS Access");
		chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		chooser.setFileFilter(fileFilter);
		if (sourceFile != null) {
			chooser.setCurrentDirectory(sourceFile.getParentFile());
		}
		int result = chooser.showOpenDialog(this);
		if (result == JFileChooser.APPROVE_OPTION) {
			sourceFile = chooser.getSelectedFile();
			dbFileEdit.setText(sourceFile.getPath());
		}
    }//GEN-LAST:event_dbFileChooseActionPerformed

    private void dstDirChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstDirChooseActionPerformed
		chooser.setDialogTitle("Выбор папки для измененных данных");
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		chooser.setFileFilter(dirFilter);
		if (destinationDir != null) {
			chooser.setCurrentDirectory(destinationDir.getParentFile());
		}
		int result = chooser.showOpenDialog(this);
		if (result == JFileChooser.APPROVE_OPTION) {
			destinationDir = chooser.getSelectedFile();
			dstDirEdit.setText(destinationDir.getPath());
		}

    }//GEN-LAST:event_dstDirChooseActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		System.setProperty("awt.useSystemAAFontSettings", "lcd");
		System.setProperty("swing.aatext", "true");
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException |
				IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				Converter converter = new Converter();
				converter.setMinimumSize(converter.getSize());
				converter.setLocationRelativeTo(null);
				converter.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dbFileChoose;
    private javax.swing.JTextField dbFileEdit;
    private javax.swing.JButton dstDirChoose;
    private javax.swing.JTextField dstDirEdit;
    private javax.swing.JButton execButton;
    // End of variables declaration//GEN-END:variables
	private File sourceFile;
	private File destinationDir;
	private final JFileChooser chooser;
	private final FileFilter fileFilter = new FileFilter() {

		@Override
		public boolean accept(File f) {
			return f.isDirectory() || f.getName().endsWith(".mdb");
		}

		@Override
		public String getDescription() {
			return "MS Access (*.mdb)";
		}

	};

	private final FileFilter dirFilter = new FileFilter() {

		@Override
		public boolean accept(File f) {
			return f.isDirectory();
		}

		@Override
		public String getDescription() {
			return "Directories";
		}

	};

}
